/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CommandesRouteImport } from './routes/commandes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsNouveauRouteImport } from './routes/clients.nouveau'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'

const CommandesRoute = CommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNouveauRoute = ClientsNouveauRouteImport.update({
  id: '/clients/nouveau',
  path: '/clients/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/commandes': typeof CommandesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/nouveau': typeof ClientsNouveauRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/commandes': typeof CommandesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/nouveau': typeof ClientsNouveauRoute
  '/clients': typeof ClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/commandes': typeof CommandesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/nouveau': typeof ClientsNouveauRoute
  '/clients/': typeof ClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/commandes'
    | '/clients/$clientId'
    | '/clients/nouveau'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/commandes'
    | '/clients/$clientId'
    | '/clients/nouveau'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/commandes'
    | '/clients/$clientId'
    | '/clients/nouveau'
    | '/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommandesRoute: typeof CommandesRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNouveauRoute: typeof ClientsNouveauRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/commandes': {
      id: '/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof CommandesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/nouveau': {
      id: '/clients/nouveau'
      path: '/clients/nouveau'
      fullPath: '/clients/nouveau'
      preLoaderRoute: typeof ClientsNouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommandesRoute: CommandesRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNouveauRoute: ClientsNouveauRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
